### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 12 >= 10 error

### ISSUE THREAD

**Issue by shyyawn** [floedermann/jobscheduler#2]
I am getting the below error, when I am trying to launch a pod on kubernetes. 

```
[ Starting automated installation ]
It is strongly recommended that you not logged in as root.
numOfPrevInstallations=0
Read pack list from xml definition.
Try to add to selection [Name: Job Scheduler and Index: 0]
Try to add to selection [Name: Database Support and Index: 2]
Try to add to selection [Name: Housekeeping Jobs and Index: 5]
Modify pack selection.
Port 40444 is available.
Port 4444 is available.
java.lang.ArrayIndexOutOfBoundsException: 12 >= 10
java.lang.ArrayIndexOutOfBoundsException: 12 >= 10
	at java.util.Vector.elementAt(Vector.java:474)
	at com.izforge.izpack.installer.AutomatedInstaller.updateInstanceCount(Unknown Source)
	at com.izforge.izpack.installer.AutomatedInstaller.doInstall(Unknown Source)
	at com.izforge.izpack.installer.Installer.main(Unknown Source)
[ Automated installation FAILED! ]
```

Something I missed? Can you point me in the direction.

**Comment by shyyawn** [comment]
Oh I think I got it. It was an older xml file with multiple ports, that was the issue. Then I had the issue of a lib, fixed that by adding   libc6-compat  in the Dockerfile. Now its a strange one:

```
|   Change owner in /opt/jobscheduler/data/scheduler to root
+-----------------------------------------------------------
... nothing to do

+-----------------------------------------------------------
|   Start JobScheduler
+-----------------------------------------------------------
	/lib64/ld-linux-x86-64.so.2 (0x7f023f2a5000)
	libjobscheduler-engine.so => /opt/jobscheduler/scheduler/lib/libjobscheduler-engine.so (0x7f023ea7d000)
	libz.so.1 => /lib/libz.so.1 (0x7f023e867000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f023f2a5000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f023f2a5000)
	libstdc++.so.6 => /opt/jobscheduler/scheduler/lib/libstdc++.so.6 (0x7f023e551000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f023f2a5000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f023f2a5000)
	libgcc_s.so.1 => /opt/jobscheduler/scheduler/lib/libgcc_s.so.1 (0x7f023e33b000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f023e0af000)

/bin/sh: /opt/jobscheduler/scheduler/bin/scheduler: not found

[ Processing finished ]
[ Writing the uninstaller data ... ]
[ Automated installation done ]
```

**Comment by floedermann** [comment]
Hey can you post your kubernetes yaml so i can check it out directly? Needing the compat lib seems a bit odd but I will test it myself and add the dependency if needed

**Comment by floedermann** [comment]
Since there was no reply I will close it for now
